<?php

namespace Src\Ordering\Infrastructure\Http\Requests;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Src\Ordering\Application\CreateOrder\CreateOrderDto;
use Src\Ordering\Application\CreateOrder\OrderItem;

class StoreOrderRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()->can('place-orders');
    }

    /**
     * @return array<string, array<int, ValidationRule|string>>
     */
    public function rules(): array
    {
        return [
            // Generated by the client (UUIDv4), so a resubmitted order fails `unique` instead of being placed twice.
            'id' => ['required', 'uuid:4', 'unique:orders,id'],
            'products' => ['required', 'array', 'min:1'],
            'products.*.product_id' => ['required', 'uuid', 'distinct', 'exists:products,id'],
            'products.*.quantity' => ['required', 'integer', 'min:1'],
        ];
    }

    /**
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'id.unique' => 'This order has already been placed.',
        ];
    }

    public function toDto(): CreateOrderDto
    {
        return new CreateOrderDto(
            $this->validated('id'),
            $this->user()->id,
            array_map(
                fn (array $item) => new OrderItem($item['product_id'], (int) $item['quantity']),
                $this->validated('products'),
            ),
        );
    }
}
